packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  - 'packages/effects/*'
  - 'packages/@core/*'
  - 'packages/@core/ui-kit/*'
  - 'packages/@core/base/*'
  - 'packages/@core/base/typings'
  - 'apps/*'
  - 'internal/vite-config'
  # exclude packages that are inside test directories
  - '!**/test/**'
